name: variants
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - conda-build
  - R
  - gatk
  - samtools
  - pysam
  - star
  - bwa
  - bowtie2
  - numpy=1.22.4
  - python=3.10.6
  - scipy=1.9.0
  - seaborn=0.12.0
  - statsmodels=0.13.2
  - cmake
  - git
  - pip
  - pip:
    - pandas==1.4.4
